# Generated by Django 3.1.5 on 2021-01-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('symbole', models.CharField(max_length=255, unique=True)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
